<?php

/**
 * @file
 * Contains iucn_site.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Validation\Plugin\Validation\Constraint;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function iucn_site_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iucn_site module.
    case 'help.page.iucn_site':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('IUCN site related functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function iucn_site_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'site') {
    if (isset($fields['field_wdpa_id'])) {
      $fields['field_wdpa_id']->addConstraint('UniqueField',[]);
    }
    if (isset($fields['field_unesco_id'])) {
      $fields['field_unesco_id']->addConstraint('UniqueField',[]);
    }
    if (isset($fields['field_site_id'])) {
      $fields['field_site_id']->addConstraint('UniqueField',[]);
    }
  }
}

/**
 * {@inheritdoc}
 */
function iucn_site_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] == 'node_title') {
    if (isset($variables['items'][0]['content'][0]['#context']['entity_url'])) {
      /** @var \Drupal\Node\NodeInterface $node */
      $node = $variables['element']['#object'];
      if ($node->hasField('field_external_website')) {
        if (!empty($node->get('field_external_website')->getValue())) {
          $ext_link = $node->get('field_external_website')->getValue()[0]['uri'];
          $variables['items'][0]['content'][0]['#context']['entity_url'] = Url::fromUri($ext_link, array('attributes' => array('target' => '_blank')));
        }
      }
    }
  }
}

/**
 * {@inheritdoc}
 */
function iucn_site_preprocess_page_title(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && $node->type->target_id == 'publication') {
    $variables['title'] = t('Publications');
  }
}


/**
 * Implements hook_node_presave().
 */
function iucn_site_node_presave(\Drupal\Core\Entity\EntityInterface $node) {
  $default_language = \Drupal::languageManager()->getDefaultLanguage()->getId();

  if (($node->bundle() == 'site' || $node->bundle() == 'publication')  && $node->language()->getId() == $default_language && \Drupal::request()->attributes->get('_entity_form') != 'node.delete') {
    if ($node->isNew()) {
      $old_node = $node;
    }
    else {
      $old_node = Node::load($node->id());
    }
    $languages = \Drupal::languageManager()->getLanguages();
    foreach ($languages as $language) {
      $lang_id = $language->getId();
      if ($lang_id != $default_language) {
        if ($node->hasTranslation($lang_id)) {
          if ($node->getTranslation($lang_id)->getTitle() == $old_node->getTitle()) {
            $node->getTranslation($lang_id)->setTitle($node->getTitle());
            $node->getTranslation($lang_id)->set('body', $node->get('body')->getValue());
          }
        }
        else {
            $node->addTranslation($lang_id, [
              'title' => $node->getTitle(),
              'body' => $node->get('body')->getValue(),
            ]
            );
        }
      }
    }
  }

  // Create a new json file containing site geoJson and append it if another one doesn't exist already.
  if ($node->bundle() == 'site') {
    \Drupal::service('iucn_site.utils')->createGeoJson($node);
  }
}

/**
 * Implements hook_form_alter.
 */
function iucn_site_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    if (isset($form['#info']['filter-search_api_fulltext']['label'])) {
      $form['keys']['#attributes']['placeholder'] = t($form['#info']['filter-search_api_fulltext']['label']);
    }
  }
}

/**
 * Implements hook_theme().
 */
function iucn_site_theme($existing, $type, $theme, $path) {
  return [
    'explore_map' => [
      'variables' => [
        'title' => NULL,
        'button_title' => NULL,
        'button_prefix' => NULL,
        'button_url' => NULL,
        'button_url_target' => NULL,
      ],
    ]
  ];
}

function iucn_site_node_update(Drupal\node\Entity\Node $node) {
  // Add the site to the update_geojson queue on node update.
  if ($node->bundle() == 'site') {
    $queue_factory = \Drupal::service('queue');
    $queue = $queue_factory->get('cron_site_update_geojson');
    $queue->createItem($node->id());
  }
}
