<?php

/**
 * @file
 * Contains iucn_site.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Validation\Plugin\Validation\Constraint;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function iucn_site_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iucn_site module.
    case 'help.page.iucn_site':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('IUCN site related functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function iucn_site_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'site') {
    if (isset($fields['field_wdpa_id'])) {
      $fields['field_wdpa_id']->addConstraint('UniqueField',[]);
    }
    if (isset($fields['field_unesco_id'])) {
      $fields['field_unesco_id']->addConstraint('UniqueField',[]);
    }
    if (isset($fields['field_site_id'])) {
      $fields['field_site_id']->addConstraint('UniqueField',[]);
    }
  }
}

/**
 * {@inheritdoc}
 */
function iucn_site_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] == 'node_title') {
    if (isset($variables['items'][0]['content'][0]['#context']['entity_url'])) {
      /** @var \Drupal\Node\NodeInterface $node */
      $node = $variables['element']['#object'];
      if ($node->hasField('field_external_website')) {
        if (!empty($node->get('field_external_website')->getValue())) {
          $ext_link = $node->get('field_external_website')->getValue()[0]['uri'];
          $variables['items'][0]['content'][0]['#context']['entity_url'] = Url::fromUri($ext_link, array('attributes' => array('target' => '_blank')));
        }
      }
    }
  }
}
