version: '2.0'

services:

  nginx:
    image: nginx:1.13
    depends_on:
      - php71
    env_file:
      - .env
    volumes:
      - .docker/conf-nginx/globals.conf:/etc/nginx/conf.d/globals.conf:ro
      - .docker/conf-nginx/project.conf:/etc/nginx/conf.d/project.conf:ro

  php71:
    image: eaudeweb/php-fpm:7.1-1.0.1
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.3
    env_file:
      - .env
    volumes:
      - .docker/conf-mysqld/server.cnf:/etc/mysql/conf.d/server.cnf
