version: '2.0'

services:

  nginx-front:
    image: nginx:1.13
    volumes:
      - .docker/conf-nginx/globals.conf:/etc/nginx/conf.d/globals.conf
      - .docker/conf-nginx/varnish.conf:/etc/nginx/conf.d/varnish.conf
    depends_on:
      - varnish
    env_file:
      - .env

  varnish:
    image: eeacms/varnish
    volumes:
      - .docker/conf-varnish/drupal.vcl:/etc/varnish/conf.d/default.vcl
      - .docker/conf-varnish/secret:/etc/varnish/secret
    depends_on:
      - nginx
    env_file:
      - .env

  nginx:
      image: nginx:1.13
      depends_on:
        - php71
      env_file:
        - .env
      volumes:
        - .docker/conf-nginx/globals.conf:/etc/nginx/conf.d/globals.conf:ro
        - .docker/conf-nginx/project.conf:/etc/nginx/conf.d/project.conf:ro

  php71:
    image: eaudeweb/php-fpm:7.1-1.0.1
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.3
    env_file:
      - .env
    volumes:
      - .docker/conf-mysqld/server.cnf:/etc/mysql/conf.d/server.cnf
