<?php

use \Drupal\iucn_who_core\ToolbarHandler;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\views\Views;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Breadcrumb\BreadcrumbBuilderInterface;
use Drupal\Core\Form\FormStateInterface;

define('TAXONOMY_SITE_CONSERVATION_RATING', 'conservation_rating');

/**
 * Implements hook_views_data_alter().
 */
function iucn_who_core_views_data_alter(array &$data) {
  $data['users']['user_assessor'] = array(
    'title' => t('Assessor'),
    'field' => array(
      'title' => t('Assessor'),
      'help' => t('Assessor.'),
      'id' => 'iucn_who_core_assessor',
    ),
  );
  $data['users']['user_coordinator'] = array(
    'title' => t('Coordinator'),
    'field' => array(
      'title' => t('Coordinator'),
      'help' => t('Coordinator.'),
      'id' => 'iucn_who_core_coordinator',
    ),
  );
  $data['users']['user_reviewer'] = array(
    'title' => t('Reviewer'),
    'field' => array(
      'title' => t('Reviewer'),
      'help' => t('Reviewer.'),
      'id' => 'iucn_who_core_reviewer',
    ),
  );
}
/**
 * Implements hook_toolbar().
 */
function iucn_who_core_toolbar() {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(ToolbarHandler::class)
    ->toolbar();
}

/**
 * Replace user text field with select box.
 */
function iucn_who_core_add_users_by_role(&$form, $field_id, $display_id, $empty_option) {
  if (empty($form[$field_id])) {
    return;
  }
  $view = \Drupal\views\Views::getView('users_by_roles');
  $view->setDisplay($display_id);
  $view->execute();
  $options = [];
  foreach ($view->result as $row) {
    $options[$row->uid] = $row->_entity->getAccountName();
  }
  $form[$field_id]['#type'] = 'select';
  $form[$field_id]['#multiple'] = FALSE;
  $form[$field_id]['#empty_option'] = $empty_option;
  $form[$field_id]['#options'] = $options;
  unset($form[$field_id]['#size']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the artist options on artwork pages.
 */
function iucn_who_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!in_array($form['#id'], [
    'views-exposed-form-account-assignments-block-1',
    'views-exposed-form-account-assignments-block-2',
    'views-exposed-form-account-assignments-block-3',
    'views-exposed-form-account-assignments-block-4',
    'views-exposed-form-account-assignments-block-5',
  ])) {
    return;
  }
  // Assessor list.
  iucn_who_core_add_users_by_role($form, 'assessor_id', 'entity_reference_2', t('- Assessor -'));
  // Reviewer list.
  iucn_who_core_add_users_by_role($form, 'reviewers_id', 'entity_reference_3', t('- Reviewer -'));
  // Coordinator list.
  iucn_who_core_add_users_by_role($form, 'coordinator_id', 'entity_reference_1', t('- Coordinator -'));
}

function iucn_who_core_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if (!(\Drupal::currentUser()->hasPermission('access content'))) {
    return;
  }
  $current_uri = \Drupal::request()->getRequestUri();
  if (!strpos($current_uri, 'admin/dashboard')) {
    return;
  }
  if ($entity->getEntityTypeId() !== 'node') {
    return;
  }
  if ($entity->getType() === 'site_assessment') {
    $operations['edit']['url'] = Url::fromRoute('entity.node.edit_form', ['node' => $entity->id()]);
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function iucn_who_core_page_attachments_alter(array &$attachments) {
  // Trim metatag desc.
  if (!empty($attachments['#attached']['html_head'])) {
    foreach ($attachments['#attached']['html_head'] as &$tag) {
      $is_meta = !empty($tag[0]['#tag']) && $tag[0]['#tag'] == 'meta';
      $is_desc = $is_meta && !empty($tag[0]['#attributes']['name']) && $tag[0]['#attributes']['name'] == 'description';
      if ($is_desc) {
        $summary = text_summary($tag[0]['#attributes']['content'], 'plain_text', 300);
        $tag[0]['#attributes']['content'] = preg_replace('/\n|\r|\t/m', ' ', $summary);
      }
    }
  }
  _remove_header_links($attachments);
}

/**
 * Implements hook_entity_view_alter().
 */
function iucn_who_core_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Cheking view_mode for node.
  if ($build['#view_mode'] !== 'full' && $entity Instanceof NodeInterface) {
    return;
  }
  _remove_header_links($build);
}

function _remove_header_links(array &$attachments) {
  // Cheking html_head_link on attached tags in head.
  if (!isset($attachments['#attached']['html_head_link'])) {
    return;
  }
  // Array to unset.
  $unset_html_head_link = [
    'delete-form',
    'edit-form',
    'version-history',
    'revision',
    'display',
    'drupal:content-translation-overview',
    'drupal:content-translation-add',
    'drupal:content-translation-edit',
    'drupal:content-translation-delete',
    'shortlink',
  ];
  // Unset loop.
  foreach ($attachments['#attached']['html_head_link'] as $key => $value) {
    if (isset($value[0]['rel']) && in_array($value[0]['rel'], $unset_html_head_link)) {
      unset($attachments['#attached']['html_head_link'][$key]);
    }
  }
}

/**
 * Implements hook_theme().
 */
function iucn_who_core_theme($existing, $type, $theme, $path) {
  return [
    'benefits_map_block' => [
      'variables' => [
        'markup_map' => null,
        'categories' => [],
        'empty_selection_placeholder_markup' => null,
      ]
    ],
    'benefits_map_site_detail' => [
      'variables' => [
        'status' => [ 'label' => null, 'id' => null ],
        'title' => null,
        'country' => [ 'label' => null ],
        'thumbnail' => null,
        'inscription' => null,
        'link' => null,
        'stat_values' => null,
        'stat_threat' => null,
        'stat_protection' => null,
      ]
    ],
  ];
}

/**
 * Implements hook_path_insert().
 */
function iucn_who_core_path_insert($path) {
  _iucn_who_multilingual_path($path);
}

/**
 * Implements hook_path_update().
 */
function iucn_who_core_path_update($path) {
  _iucn_who_multilingual_path($path);
}

function _iucn_who_multilingual_path($path) {
  if (preg_match('/^\/node\/[0-9]*$/', $path['source'])) {
    if ($path['langcode'] == 'en') {
      foreach (\Drupal::languageManager()->getLanguages() as $language) {
        if ($language->getId() == 'en') {
          continue;
        }
        $conditions = [
          'source' => $path['source'],
          'langcode' => $language->getId(),
        ];
        $existing_alias = \Drupal::service('path.alias_storage')->load($conditions);
        if (empty($existing_alias)) {
          // Not translated.
          $path = \Drupal::service('path.alias_storage')->save($path['source'], $path['alias'], $language->getId());
        }
        elseif (!empty($path['original']['alias']) && $path['original']['alias'] == $existing_alias['alias']) {
          // Update alias.
          $existing_alias['alias'] = $path['alias'];
          $path = \Drupal::service('path.alias_storage')->save($path['source'], $path['alias'], $language->getId(), $existing_alias['pid']);
        }
      }
    }
  }
}

function iucn_who_core_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
  $parameters = $route_match->getParameters()->all();

  $cache_tags = $breadcrumb->getCacheTags();
  $cache_context = $breadcrumb->getCacheContexts();
  $cache_max = $breadcrumb->getCacheMaxAge();

  // Custom breadcrumb for Webforms.
  if (isset($parameters['webform']) && gettype($parameters['webform']) == 'object' && in_array($parameters['webform']->id(), ['site_feedback', 'ask_a_question'])) {
    $new_breadcrumb = new Breadcrumb();
    foreach ($breadcrumb->getLinks() as $key => $val) {
      if ($key == 0) {
        $new_breadcrumb->addLink(Link::createFromRoute(t('Home'), '<front>'));
        $new_breadcrumb->addLink(Link::createFromRoute(t('More'), '<none>'));
        $nid = 1234;
        $url_object = Url::fromRoute('entity.node.canonical', ['node' => $nid], ['absolute' => FALSE]);
        $url_node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
        $new_breadcrumb->addLink(Link::fromTextAndUrl($url_node->getTitle(), $url_object));

      }
    }
    $breadcrumb = $new_breadcrumb;
  }

  // Custom breadcrumb for sites_search view.
  if (isset($parameters['view_id']) && $parameters['view_id'] == 'publications' && isset($parameters['display_id']) && $parameters['display_id'] == 'publications_page_database') {
    $new_breadcrumb = new Breadcrumb();
    $new_breadcrumb->addLink(Link::createFromRoute(t('Home'), '<front>'));
    $new_breadcrumb->addLink(Link::createFromRoute(t('More'), '<none>'));
    $breadcrumb = $new_breadcrumb;
  }

  // Custom breadcrumb for frequently_asked_questions view.
  if (isset($parameters['view_id']) && $parameters['view_id'] == 'frequently_asked_questions' && isset($parameters['display_id']) && $parameters['display_id'] == 'page_1') {
    $new_breadcrumb = new Breadcrumb();
    $new_breadcrumb->addLink(Link::createFromRoute(t('Home'), '<front>'));
    $new_breadcrumb->addLink(Link::createFromRoute(t('More'), '<none>'));
    $new_breadcrumb->addLink(Link::createFromRoute(t('FAQ'), '<none>'));
    $breadcrumb = $new_breadcrumb;
  }

  // Custom breadcrumb for sites_search view.
  if (isset($parameters['view_id']) && $parameters['view_id'] == 'sites_search' && isset($parameters['display_id']) && $parameters['display_id'] == 'sites_search_page_database') {
    $new_breadcrumb = new Breadcrumb();
    $new_breadcrumb->addLink(Link::createFromRoute(t('Home'), '<front>'));
    $new_breadcrumb->addLink(Link::createFromRoute(t('Explore sites'), '<none>'));
    $breadcrumb = $new_breadcrumb;
  }

  // Custom breadcrumb for publication ctype.
  if (!empty($parameters['node']) && ($parameters['node'] instanceof NodeInterface) && $parameters['node']->getType() == 'publication') {
    $new_breadcrumb = new Breadcrumb();
    foreach ($breadcrumb->getLinks() as $key => $val) {
      $new_breadcrumb->addLink($val);
      if ($key == 0) {
        $new_breadcrumb->addLink(Link::createFromRoute(t('More'), '<none>'));
      }
    }
    $breadcrumb = $new_breadcrumb;
  }

  // Custom breadcrumb for news view.
  if (isset($parameters['view_id']) && $parameters['view_id'] == 'news' && isset($parameters['display_id']) && $parameters['display_id'] == 'page_1') {
    $new_breadcrumb = new Breadcrumb();
    foreach ($breadcrumb->getLinks() as $key => &$val) {
      $new_breadcrumb->addLink($val);
    }
    $new_breadcrumb->addLink(Link::createFromRoute(t('News'), '<none>'));
    $breadcrumb = $new_breadcrumb;
  }

  // Custom breadcrumb for news ctype.
  if (!empty($parameters['node']) && ($parameters['node'] instanceof NodeInterface) && $parameters['node']->getType() == 'news') {
    $new_breadcrumb = new Breadcrumb();
    foreach ($breadcrumb->getLinks() as $key => $val) {
      $new_breadcrumb->addLink($val);
      if ($key == 0) {
        $new_breadcrumb->addLink(Link::createFromRoute(t('More'), '<none>'));
      }

    }
    $breadcrumb = $new_breadcrumb;
  }


  if (!empty($parameters['node']) && ($parameters['node'] instanceof NodeInterface) && $parameters['node']->getType() == 'site') {
    $new_breadcrumb = new Breadcrumb();


    foreach ($breadcrumb->getLinks() as $key => &$val) {
      if ($key == 1){
        /** @var  Drupal\Core\Link $val */
        $val->setText(t('Explore sites'));
      }
      if ($key != 2){
        $new_breadcrumb->addLink($val);
      }
    }
    $breadcrumb = $new_breadcrumb;
  }

  $menu_items = iucn_who_get_all_menu('main');

  // Remove duplicate labels from breadcrumb.
  $new_breadcrumb = new Breadcrumb();
  $text = NULL;
  foreach ($breadcrumb->getLinks() as $key => $val) {

    $currentLanguage = '';
    $default_language = \Drupal::languageManager()->getDefaultLanguage()->getId();
    $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    if ($default_language != $current_language) {
      $currentLanguage = "/$current_language";
    }

    $url = $currentLanguage . $val->getUrl()->toString();

    if (array_key_exists($url, $menu_items)) {
      /** @val \Drupal\Core\Link $val */
      $val->setText($menu_items[$url]);
    }
    if ($text != $val->getText()) {
      $new_breadcrumb->addLink($val);
    }
    $text = $val->getText();
    /** @val \Drupal\Core\Link $val */
  }
  $breadcrumb = $new_breadcrumb;


  $breadcrumb->addCacheTags($cache_tags);
  $breadcrumb->addCacheContexts($cache_context);
  $breadcrumb->addCacheContexts(['url']);
  $breadcrumb->mergeCacheMaxAge($cache_max);

}

function iucn_who_get_all_menu($menu_name){
  $menu = iucn_who_get_menu($menu_name);
  $menu_items = [];
  foreach ($menu['#items'] as $item) {
    if ($item['url']->toString()) {
      $menu_items[$item['url']->toString()] = $item['title'];
    }
  }
  $menu = iucn_who_get_menu($menu_name, 2);
  foreach ($menu['#items'] as $item) {
    if ($item['url']->toString()) {
      $menu_items[$item['url']->toString()] = $item['title'];
    }
  }
  return $menu_items;
}

function iucn_who_get_menu($menu_name,$depth = 1) {

  $menu_tree = \Drupal::menuTree();
  // Build the typical default set of menu tree parameters.
  $parameters = $menu_tree->getCurrentRouteMenuTreeParameters($menu_name);
  // Load the tree based on this set of parameters.
  $parameters->setMinDepth($depth);
  $tree = $menu_tree->load($menu_name, $parameters);
  // Transform the tree using the manipulators you want.
  $manipulators = array(
    // Only show links that are accessible for the current user.
    array('callable' => 'menu.default_tree_manipulators:checkAccess'),
    // Use the default sorting of menu links.
    array('callable' => 'menu.default_tree_manipulators:generateIndexAndSort'),
  );
  $tree = $menu_tree->transform($tree, $manipulators);
  // Finally, build a renderable array from the transformed tree.
  $menu = $menu_tree->build($tree);

  return $menu;
}

function mymodule_get_menu_items($menu_name) {

  $menu_data = mymodule_get_menu($menu_name);

  foreach ($menu_data['#items'] as $item) {
    if ($item['url']->getRouteName() == '') {
      $menu[] = [$item['title'] => $item['url']->getRouteName()];
    }
    else {
      $menu[] = [$item['title'] => $item['url']->getInternalPath()];
    }
  }

  return $menu;
}

function iucn_who_core_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['reset_password'] = [
      '#type' => 'link',
      '#title' => t('Reset your password'),
      '#url' => Url::fromRoute('user.pass'),
      '#attributes' => ['class' => ['btn', 'btn-primary']],
      '#weight' => '200',
    ];
  }
}


/**
 * Implements hook_preprocess_menu().
 *
 * Hides links from tools menu, if user doesn't have access rights.
 */
function iucn_who_core_preprocess_menu(&$variables) {
  if (empty($variables['items'])) {
    return;
  }
  if (!empty($variables['menu_name']) && $variables['menu_name'] == 'tools') {
    if (!admin_toolbar_links_access_filter_user_has_admin_role($variables['user'])) {
      $items = &$variables['items'];
      foreach ($variables['items'] as $route => &$item) {
        $route_name = $route;
        $route_params = [];
        if (!empty($item['original_link'])) {
          /** @var \Drupal\Core\Menu\MenuLinkBase $original_link */
          $original_link = $item['original_link'];
          if ($original_link->getUrlObject()->isExternal()) {
            // Do not filter external URL at all.
            continue;
          }
          $route_name = $original_link->getRouteName();
          $route_params = $original_link->getRouteParameters();
        }

        // Check, if user has access rights to the route.
        if (!\Drupal::accessManager()->checkNamedRoute($route_name, $route_params)) {
          unset($items[$route]);
        }
        else {
          if (!empty($items[$route]['below'])) {
            // Recursively call this function for the child items.
            admin_toolbar_links_access_filter_filter_non_accessible_links($items[$route]['below']);
          }
          if (empty($items[$route]['below'])) {
            unset($items[$route]);
          }
        }
      }
    }
  }
}
