<?php


/**
 * Implements hook_theme().
 */
function iucn_who_homepage_theme($existing, $type, $theme, $path) {
  return [
    'homepage_map_block' => [
      'variables' => [
        'markup_map' => null,
        'sites_total_count' => null,
        'conservation_ratings' => [],
        'search_form' => null,
        'empty_selection_placeholder_markup' => null,
        'block_footer_text' => null,
      ]
    ],
    'homepage_map_site_detail' => [
      'variables' => [
        'status' => [ 'label' => null, 'id' => null ],
        'title' => null,
        'country' => [ 'label' => null ],
        'thumbnail' => null,
        'inscription' => null,
        'link' => null,
        'stat_values' => null,
        'stat_threat' => null,
        'stat_protection' => null,
      ]
    ],
    'homepage_statistics' => [
      'variables' => ['statistics' => null]
    ],
    'homepage_report' => ['variables' => [
      'title' => null, 'subtitle' => null, 'file_url' => null
      ]
    ]
  ];
}