<?php

use \Drupal\Core\StringTranslation\TranslatableMarkup;
use \Drupal\google_maps_api\Form\GMConfigurationForm;

function google_maps_api_library_info_build() {
  $libraries = [];
  $api_key = \Drupal::state()->get(GMConfigurationForm::CONFIG_NAME);
  if (!empty($api_key)) {
    drupal_set_message('Google Maps API is not correctly configured, maps will not work. Please contact technical support', 'error');
  }
  $url = sprintf('https://maps.googleapis.com/maps/api/js?key=%s&callback=initMap', $api_key);
  $libraries['core'] = [
    'version' => '1.x',
    'js' => [
      $url => [
        'type' => 'external', 'attributes' => [ 'defer' => TRUE, 'async' => TRUE ]
      ]
    ]
  ];
  return $libraries;
}


/**
 * Implements hook_requirements().
 */
function google_maps_api_requirements($phase) {
  if ($phase == 'runtime') {
    $api_key = \Drupal::state()->get(GMConfigurationForm::CONFIG_NAME);
    if (empty($api_key)) {
      return [
        'google_mapis_api' => [
          'title' => t('Google Maps API Key'),
          'description' => t(
            'Google Maps API is not correctly configured, maps will not work, press <a href="@url">here</a> to configure it',
            [
              '@url' => \Drupal\Core\Url::fromRoute('google_maps_api.config_form')
                ->toString()
            ]
          ),
          'severity' => REQUIREMENT_ERROR,
          'value' => 'Key is empty'
        ]
      ];
    }
  }
}