<?php

/**
 * @file
 * Contains iucn_config_ignore.module.
 */


use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Config\StorageInterface;
use Drupal\Core\Config\StorageComparer;
use Drupal\Core\Config\FileStorage;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function iucn_config_ignore_form_config_admin_import_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  drupal_set_message(t('The following items in your active configuration are ignored by the configuration import and they will not be lost on the next import.
<div class="item-list"><ul><li>system.site.mail</li><li>webform.webform.ask_a_question.to_mail</li><li>webform.webform.site_feedback.to_mail</li></ul></div>'), 'warning');
}