<?php

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function iucn_fields_field_widget_options_select_form_alter(&$element, \Drupal\Core\Form\FormStateInterface &$form_state, $context) {
  if ($element['#entity_type'] != 'paragraph') {
    return;
  }
  /** @var \Drupal\Core\Field\EntityReferenceFieldItemList $items */
  $items = $context['items'];
  /** @var \Drupal\field\Entity\FieldConfig $field_definition */
  $field_definition = $items->getFieldDefinition();
  $target_type = $field_definition->getSetting('target_type');
  if ($target_type != 'taxonomy_term') {
    return;
  }
  $assessment = $form_state->getFormObject()->getEntity();
  if (!$assessment instanceof \Drupal\paragraphs\ParagraphInterface) {
    return;
  }
  $assessment_year = $assessment->field_as_cycle->value;
  $options = &$element['#options'];
  $removed_tids = [];
  foreach ($options as $tid => &$label) {
    $term = Term::load($tid);
    if (empty($term)) {
      continue;
    }
    $term_name = $term->getName();
    /** @var \Drupal\iucn_fields\Plugin\TermAlterService $term_alter_service */
    $term_alter_service = \Drupal::service('iucn_fields.term_alter');
    if ($term_alter_service->isTermHiddenForYear($tid, $assessment_year)) {
      $removed_tids[] = $tid;
      unset($options[$tid]);
      continue;
    }
    $term_new_name = $term_alter_service->getTermLabelForYear($tid, $assessment_year);
    if (!empty($term_new_name)) {
      $label = str_replace($term_name, $term_new_name, $label);
    }
  }

  foreach ($element['#default_value'] as $idx => $value) {
    if (in_array($value, $removed_tids)) {
      unset($element['#default_value'][$idx]);
    }
  }

}

/**
 * Implements hook_preprocess_field().
 */
function iucn_fields_preprocess_field(&$variables) {
  if ($variables['element']['#entity_type'] != 'paragraph' || $variables['element']['#field_type'] != 'entity_reference') {
    return;
  }
  /** @var \Drupal\Core\Field\EntityReferenceFieldItemList $items */
  $items = $variables['element']['#items'];
  /** @var \Drupal\field\Entity\FieldConfig $field_definition */
  $field_definition = $items->getFieldDefinition();
  $target_type = $field_definition->getSetting('target_type');
  if ($target_type != 'taxonomy_term') {
    return;
  }
  $field_name = $variables['field_name'];
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['element']['#object'];
  /** @var \Drupal\node\Entity\Node $assessment */
  $assessment = $paragraph->getParentEntity();
  if ($assessment->getType() != 'site_assessment') {
    return;
  }
  $assessment_year = $assessment->field_as_cycle->value;
  /** @var \Drupal\taxonomy\Entity\Term $term */
  $term = $paragraph->{$field_name}->entity;

  /** @var \Drupal\iucn_fields\Plugin\TermAlterService $term_alter_service */
  $term_alter_service = \Drupal::service('iucn_fields.term_alter');
  $is_hidden = $term_alter_service->isTermHiddenForYear($term->id(), $assessment_year);
  if ($is_hidden) {
    $term->name->value = '';
  }
  else {
    $term_label = $term_alter_service->getTermLabelForYear($term->id(), $assessment_year);
    if (!empty($term_label)) {
      $term->name->value = $term_label;
    }
  }
}
