<?php

/**
 * @file
 * Contains iucn_diff_revisions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iucn_diff_revisions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iucn_diff_revisions module.
    case 'help.page.iucn_diff_revisions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function iucn_diff_revisions_theme() {
  return [
    'iucn_diff_revisions' => [
      'render element' => 'children',
    ],
  ];
}
