<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Drupal\iucn_assessment\Form\NodeSiteAssessmentForm;
use Drupal\iucn_assessment\Form\NodeSiteAssessmentStateChangeForm;
use Drupal\iucn_assessment\Form\NodeSiteAssessmentAssignUsersForm;
use Drupal\iucn_assessment\Form\ParagraphAsSiteThreatForm;
use Drupal\user\Entity\User;
use Drupal\workflow\Entity\WorkflowState;
use Drupal\Core\Url;
use Drupal\iucn_assessment\Plugin\AssessmentWorkflow;
use Drupal\Core\Render\Element;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\Core\Template\Attribute;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;
use Drupal\iucn_assessment\Form\ParagraphAsSiteBenefitForm;

function iucn_assessment_theme() {
  return [
    'assessment_horizontal_tabs' => array(
      'render element' => 'element',
      'template' => 'assessment-horizontal-tabs',
      'file' => 'templates/theme.inc',
    ),
    'field_group_html_element_list' => [
      'render element' => 'element',
      'template' => 'field-group-html-element-list',
    ],
    'rating_image_switcher' => [
      'render element' => 'element',
      'template' => 'rating-image-switcher',
    ],
    'assessment_fieldset' => [
      'render element' => 'element',
    ],
  ];

}

/**
 * Prepares variables for fieldset element templates.
 *
 * Default template: fieldset.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #attributes, #children, #description, #id, #title,
 *     #value.
 */
function template_preprocess_assessment_fieldset(&$variables) {
  $element = $variables['element'];
  Element::setAttributes($element, ['id']);
  RenderElement::setAttributes($element);
  $variables['attributes'] = isset($element['#attributes']) ? $element['#attributes'] : [];
  $variables['fields_titles'] = isset($element['#fields_titles']) ? explode('|', $element['#fields_titles']) : [];
  $variables['prefix'] = isset($element['#field_prefix']) ? $element['#field_prefix'] : NULL;
  $variables['suffix'] = isset($element['#field_suffix']) ? $element['#field_suffix'] : NULL;
  $variables['title_display'] = isset($element['#title_display']) ? $element['#title_display'] : NULL;
  $variables['children'] = $element['#children'];
  $variables['required'] = !empty($element['#required']) ? $element['#required'] : NULL;

  if (isset($element['#title']) && $element['#title'] !== '') {
    $variables['legend']['title'] = ['#markup' => $element['#title']];
  }

  $variables['legend']['attributes'] = new Attribute();
  // Add 'visually-hidden' class to legend span.
  if ($variables['title_display'] == 'invisible') {
    $variables['legend_span']['attributes'] = new Attribute(['class' => ['visually-hidden']]);
  }
  else {
    $variables['legend_span']['attributes'] = new Attribute();
  }

  if (!empty($element['#description'])) {
    $description_id = $element['#attributes']['id'] . '--description';
    $description_attributes['id'] = $description_id;
    $variables['description']['attributes'] = new Attribute($description_attributes);
    $variables['description']['content'] = $element['#description'];

    // Add the description's id to the fieldset aria attributes.
    $variables['attributes']['aria-describedby'] = $description_id;
  }

  // Suppress error messages.
  $variables['errors'] = NULL;
}

/**
 * Implements hook_theme_suggestions_alter().
 *
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function iucn_assessment_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  switch ($hook) {
    case 'assessment_horizontal_tabs':
      $element = $variables['element'];

      $name = $element['#group_name'];
      $entity_type = $element['#entity_type'];
      $bundle = $element['#bundle'];

      $wrapper = '';
      if (isset($element['#wrapper_element'])) {
        $wrapper = $element['#wrapper_element'];
        $suggestions[] = $hook . '__' . $wrapper;
      }

      $suggestions[] = $hook . '__' . $entity_type;
      $suggestions[] = $hook . '__' . $bundle;
      $suggestions[] = $hook . '__' . $name;

      if ($wrapper) {
        $suggestions[] = $hook . '__' . $entity_type . '__' . $wrapper;
      }

      $suggestions[] = $hook . '__' . $entity_type . '__' . $bundle;
      $suggestions[] = $hook . '__' . $entity_type . '__' . $name;

      if ($wrapper) {
        $suggestions[] = $hook . '__' . $entity_type . '__' . $bundle . '__' . $wrapper;
      }
      $suggestions[] = $hook . '__' . $entity_type . '__' . $bundle . '__' . $name;
      break;
  }

}

/**
 * Implements hook_entity_form_display_alter().
 */
function iucn_assessment_entity_form_display_alter(&$form_display, $context) {
  $id = $context['entity_type'] . '.' . $context['bundle'];
  if (($id == 'node.site_assessment') || ($context['entity_type'] == 'paragraph')) {
    $form_modes = \Drupal::entityManager()->getFormModeOptionsByBundle($context['entity_type'], $context['bundle']);
    $tab = \Drupal::request()->query->get('tab');
    $tab = str_replace('-', '_', $tab);
    if ($tab && !empty($form_modes[$tab])) {
      $entity_default_display = \Drupal::entityTypeManager()->getStorage('entity_form_display')->load($id . '.' . $tab);
      if ($entity_default_display) {
        $form_display = $entity_default_display;
      }
    }
  }
}


function template_preprocess_rating_image_switcher(&$variables) {
  $element = $variables['element'];
  $variables['images'] = $element['#images'];
  $variables['years'] = $element['#years'];

  $iucn_config = \Drupal::config('iucn_who.settings');
  $year = $iucn_config->get('assessment_year');
  $variables['active_year'] = $year;

}

function template_preprocess_field_group_html_element_list(&$variables) {

  $element = $variables['element'];

  if (!empty($element['#title']) && !empty($element['#title_element'])) {
    $variables['title_element'] = $element['#title_element'];
    $variables['title'] = $element['#title'];
  }

  $variables['wrapper_element'] = $element['#wrapper_element'];
  $variables['attributes'] = $element['#attributes'];
  $variables['list'] = $element['list'];

}


/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function iucn_assessment_node_presave(Drupal\node\Entity\Node $node) {
  if ($node->bundle() == 'site' && !$node->isNew()) {
    _iucn_assessment_set_site_assessments($node);
  }
  elseif ($node->bundle() == 'site_assessment') {
    /** @var \Drupal\iucn_assessment\Plugin\AssessmentWorkflow $workflow_service */
    $workflow_service = \Drupal::service('iucn_assessment.workflow');
    $workflow_service->assessmentPreSave($node);
  }
}

/**
 * Implements hook_node_update().
 */
function iucn_assessment_node_update(Drupal\node\Entity\Node $node) {
  if ($node->bundle() == 'site_assessment' && !empty($node->field_as_site->entity)) {
    $site = $node->field_as_site->entity;
    if (!empty($site)) {
      // Reset site assessments for this site.
      _iucn_assessment_set_site_assessments($site);
      $site->save();
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function iucn_assessment_node_view(array &$build, EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  global $_iucn_assessment_is_latest_assessment;
  // Show a notice on PDF print that when is not latest.
  if ($entity->bundle() == 'site' && $view_mode == 'pdf') {
    if (empty($_iucn_assessment_is_latest_assessment)) {
      $build['#attributes']['class'][] = 'showing-old-assessment';
    }
    else {
      $build['#attributes']['class'][] = 'showing-latest-assessment';
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function iucn_assessment_preprocess_field(&$variables) {
  switch ($variables['field_name']) {
    case 'field_designation':
      $display_year = iucn_pdf_assessment_year_display($variables['element']['#object']);
      if ($display_year == \Drupal::service('iucn_assessment.assessments_year')->first()) {
        $variables['attributes']['class'][] = 'invisible';
      }
      break;

    case 'field_assessments':
      $variables['element']['#cache']['contexts'][] = 'url';
      if (!empty($variables['items'])) {
        $iucn_config = \Drupal::config('iucn_who.settings');
        $config_year = $iucn_config->get('assessment_year');
        $display_year = iucn_pdf_assessment_year_display($variables['element']['#object']);
        $showing_item = NULL;
        foreach ($variables['items'] as $item) {
          /* @var \Drupal\node\Entity\Node $assessment */
          $assessment = $item['content']['#node'];
          if ($assessment->field_as_cycle->value == $display_year
            && $assessment->access('view')) {
            $showing_item = $item;
            $variables['element']['#cache']['tags'][] = 'node:' . $assessment->id();
            break;
          }
        }

        // Handle custom revision display
        $node_revision = _iucn_assessment_display_negociate_assessment_revision();
        if ($node_revision && $node_revision->id() == $showing_item['content']['#node']->id()) {
          $showing_item['content']['#node'] = $node_revision;
          drupal_set_message(t('Showing assessment revision from @revision',
            ['@revision' => date('Y-m-d H:i', $node_revision->getRevisionCreationTime())]));
        }

        $variables['attributes']['class'][] = $config_year == $display_year ? 'showing-latest-assessment' : 'showing-old-assessment';
        $variables['items'] = !empty($showing_item) ? [$showing_item] : [];

      }
      break;

    case 'field_as_protection':
      // Sort this field by taxonomy term.
      if (empty($variables['items'][0]['content']['#paragraph'])) {
        break;
      }
      $items = $variables['items'];
      usort($items,
      function($a, $b) {
        $a_weight = 0;
        if ($a['content']['#paragraph']->field_as_protection_topic->count()) {
          $a_weight = $a['content']['#paragraph']->field_as_protection_topic->entity->getWeight();
        }
        $b_weight = 0;
        if ($b['content']['#paragraph']->field_as_protection_topic->count()) {
          $b_weight = $b['content']['#paragraph']->field_as_protection_topic->entity->getWeight();
        }
        if ($a_weight == $b_weight) {
          return 0;
        }
        return ($a_weight < $b_weight) ? -1 : 1;
      }
      );

      break;

    case 'field_as_threats_categories':
      // Hide the parent terms for this field - show only sub-categories
      /*if (count($variables['items']) == 2) {
        unset($variables['items'][0]);
      }*/
      break;

    case 'field_reference':
      // Transform links to url and trim.
      /** @var \Drupal\filter\FilterPluginManager $filter_manager */
      $filter_manager = \Drupal::service('plugin.manager.filter');
      /** @var \Drupal\filter\Plugin\FilterBase $filter */
      $filter = $filter_manager->createInstance('filter_url');
      $filter->settings['filter_url_length'] = 60;

      $items = $variables['items'];

      $value = _filter_html_escape($items[0]['content']['#context']['value']);
      $items[0]['content']['#template'] = '{{ value|raw|nl2br }}';
      $value = $filter->process($value, 'en');
      $items[0]['content']['#context']['value'] = $value->__toString();

      $variables['items'] = $items;
      break;

    case 'field_as_references_p':
      // Sort this field by string alphabetically.
      if (empty($variables['items'])) {
        break;
      }
      $items = $variables['items'];

      usort($items,
        function ($a, $b) {
          $a_string = $a['content']['#paragraph']->field_reference->value;
          $b_string = $b['content']['#paragraph']->field_reference->value;
          return (strcmp($a_string, $b_string));
        }
      );
      $variables['items'] = $items;
      break;

    case 'field_as_references':

      if (empty($variables['items'][0]['content']['#context']['value'])) {
        break;
      }

      // Transform links to url and trim.
      /** @var \Drupal\filter\FilterPluginManager $filter_manager */
      $filter_manager = \Drupal::service('plugin.manager.filter');
      /** @var \Drupal\filter\Plugin\FilterBase $filter */
      $filter = $filter_manager->createInstance('filter_url');
      $filter->settings['filter_url_length'] = 60;

      $items = $variables['items'];
      foreach ($items as &$item) {
        $value = _filter_html_escape($item['content']['#context']['value']);
        $item['content']['#template'] = '{{ value|raw|nl2br }}';
        $value = $filter->process($value, 'en');
        $item['content']['#context']['value'] = $value->__toString();
      }

      usort($items,
        function ($a, $b) {
          $a_string = $a['content']['#context']['value'];
          $b_string = $b['content']['#context']['value'];
          return (strcmp($a_string, $b_string));
        }
      );
      $variables['items'] = $items;
      break;

    case 'field_as_benefits':
      // Hide "nature conservation values" benefits for 2017 assessments.
      if (
        empty($variables['items'][0]['content']['#paragraph'])
        || $variables['element']['#object']->field_as_cycle->value == \Drupal::service('iucn_assessment.assessments_year')->first()
      ) {
        break;
      }
      foreach ($variables['items'] as $idx => &$item) {
        if ($tid = $item['content']['#paragraph']->field_as_benefits_category->target_id) {
          $storage = \Drupal::service('entity_type.manager')
            ->getStorage('taxonomy_term');
          $parent = $storage->loadParents($tid);
          $parent = reset($parent);
          if ($parent && $parent->getName() == t('Nature conservation values')) {
            unset($variables['items'][$idx]);
          }
        }
      }
      break;

    case 'field_as_threats_extent':
      foreach ($variables['items'] as $key => $item) {
        $variables['items'][$key]['content']['#plain_text'] = ', ' . $variables['items'][$key]['content']['#plain_text'];
      }
      break;

    default:
      break;
  }
}

function _iucn_assessment_display_negociate_assessment_revision(\Drupal\node\Entity\Node $node = NULL) {
  if (empty($node)) {
    // Load site from url.
    $request = \Drupal::request();
    if ($request->attributes->get('_route') !== 'entity.node.canonical') {
      return NULL;
    }
    $node = $request->attributes->get('node');
  }
  if ($node->bundle() != 'site') {
    return NULL;
  }
  $request = \Drupal::request();
  $revision = $request->get('revision');
  if (empty($revision)) {
    return NULL;
  }
  /** @var Drupal\node\Entity\Node $node_revision */
  $node_revision = \Drupal::entityTypeManager()
    ->getStorage('node')
    ->loadRevision($revision);
  if (empty($node_revision)) {
    return NULL;
  }
  foreach ($node->field_assessments as $idx => $assessment) {
    if ($node_revision && $node_revision->id() == $assessment->entity->id()) {
      drupal_set_message(t('Showing assessment revision @revision', ['@revision' => $revision]));
      return $node_revision;
    }
  }
  return NULL;
}

function _iucn_assessment_set_site_assessments($node) {
  // Set assessment field.
  $query = \Drupal::entityQuery('node');
  $query->condition('type', 'site_assessment');
  $query->condition('field_as_site.target_id', $node->id());
  $entity_ids = $query->execute();
  $field_values = [];
  if (!empty($entity_ids)) {
    foreach ($entity_ids as $id) {
      $field_values[] = ['target_id' => $id];
    }
  }
  $node->field_assessments = $field_values;

  $iucn_config = \Drupal::config('iucn_who.settings');
  $current_year = $iucn_config->get('assessment_year');

  // Set current assessment.
  $query = \Drupal::entityQuery('node');
  $query->condition('status', 1);
  $query->condition('type', 'site_assessment');
  $query->condition('field_as_site.target_id', $node->id());
  $query->condition('field_as_cycle.value', $current_year);
  $query->range(0, 1);
  $query->sort('changed', 'desc');
  $entity_ids = $query->execute();

  $field_values = [];
  if (!empty($entity_ids)) {
    $field_values[] = ['target_id' => current($entity_ids)];
  }
  $node->field_current_assessment = $field_values;


}

function iucn_assessment_field_group_pre_render(&$element, &$group, &$rendering_object) {
  global $_iucn_assessment_display_year;
  if (!empty($element['#group_name']) && $element['#group_name'] == 'group_conservation_outlook') {
    if (!empty($element['field_as_end_date']['#object']->field_as_cycle)) {
      $element['#title'] = $element['field_as_end_date']['#object']->field_as_cycle->value . ' ' . $element['#title'];
    }
  }

  // Specific request to hide show only for 2017 assessments.
  if (!empty($element['#group_name'])
    && ($element['#group_name'] == 'group_key_conservation_issues' || $element['#group_name'] == 'group_community')) {
    if (!empty($_iucn_assessment_display_year) && $_iucn_assessment_display_year != \Drupal::service('iucn_assessment.assessments_year')->first()) {
      $element['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_webform_element_alter().
 */
function iucn_assessment_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  if ($element['#webform_id'] == 'site_feedback--subject' && $element['#webform_key'] == 'subject') {
    /* @var \Drupal\node\Entity\Node $node */
    $node = \Drupal::routeMatch()->getParameter('node');
    if (is_object($node) && $node->bundle() == 'site') {
      $element['#default_value'] = t('Feedback on @site', ['@site' => $node->getTitle()]);
      $element['#attributes']['readonly'] = 'readonly';
    }
  }
}

/**
 * Implements hook_ds_pre_render_alter().
 */
function iucn_assessment_ds_pre_render_alter(array &$layout_render_array, array $context, array &$vars) {
  /** @var \Drupal\node\Entity\Node $entity */
  $entity = $context['entity'];
  if ($entity->bundle() == 'site_assessment') {
    $year = $entity->field_as_cycle->value;
    // 2017 assessments shouldn't have "Other important biodiversity values".
    if ($year != \Drupal::service('iucn_assessment.assessments_year')->first()) {
      unset(
        $vars['content']['full_assessment_values']['group_assessment_information']['group_state_and_trend_of_values']['group_assessing_current_state']['display_field_copy:node-other_biodiv_values']
      );
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function iucn_assessment_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_site_assessment_form':
    case 'node_site_assessment_edit_form':
      if ($form_id == 'node_site_assessment_edit_form') {
        $form['title']['#disabled'] = 'disabled';
      }
      NodeSiteAssessmentForm::alter($form, $form_state, $form_id);
      break;

    case 'node_site_assessment_state_change_form':
      NodeSiteAssessmentStateChangeForm::alter($form, $form_state);
      break;

    case 'node_site_assessment_assign_users_form':
      NodeSiteAssessmentAssignUsersForm::alter($form, $form_state);
      break;

    case 'node_site_assessment_iucn_modal_field_diff_form':
      unset($form['url_redirects']);
      unset($form['#fieldgroups']);
      unset($form['#group_children']);
      break;

    case 'paragraph_as_site_threat_iucn_modal_paragraph_add_form':
    case 'paragraph_as_site_threat_iucn_modal_paragraph_edit_form':
    case 'paragraph_as_site_threat_iucn_modal_paragraph_diff_form':
      ParagraphAsSiteThreatForm::alter($form, $form_state, $form_id);
      break;

    case 'paragraph_as_site_benefit_iucn_modal_paragraph_add_form':
    case 'paragraph_as_site_benefit_iucn_modal_paragraph_edit_form':
    case 'paragraph_as_site_benefit_iucn_modal_paragraph_diff_form':
      ParagraphAsSiteBenefitForm::alter($form, $form_state, $form_id);
      break;

    case 'paragraph_as_site_reference_iucn_modal_paragraph_add_form':
      $form['field_reference']['widget'][0]['value']['#description'] = t('You can add multiple references at once, one per line.');
      break;

    case 'paragraph_as_site_value_wh_iucn_modal_paragraph_add_form':
    case 'paragraph_as_site_value_wh_iucn_modal_paragraph_edit_form':
    case 'paragraph_as_site_value_wh_iucn_modal_paragraph_diff_form':
      $form['field_as_values_value']['#disabled'] = TRUE;
      break;

    case 'revision_overview_form':
      // When messing with the revision creation workflow, the position of
      // the default revision is not always the first on the /revisions page.
      // This is a workaround to fix this issue.
      $revisions = $form['node_revisions_table'];
      $current_revision = NULL;
      foreach ($revisions as $key => $revision) {
        if (!is_int($key)) {
          continue;
        }
        if (empty($revision['#attributes']['class'])) {
          continue;
        }
        $classes = $revision['#attributes']['class'];
        if (in_array('revision-current', $classes)) {
          $current_revision = $key;
          break;
        }
      }
      if (!empty($current_revision)) {
        $revision = $form['node_revisions_table'][$current_revision];
        unset($form['node_revisions_table'][$current_revision]);
        array_unshift($form['node_revisions_table'], $revision);
      }
      break;

    case 'user_form':
    case 'user_register_form':
      $form['account']['roles']['#access'] = \Drupal::currentUser()->hasPermission('administer users');
      break;

    case 'views_exposed_form':
      if (strpos($form['#id'], 'views-exposed-form-account-assignments-block') == 0) {
        $form['actions']['submit']['#ajax']['disable-refocus'] = TRUE;
      }
      break;
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function iucn_assessment_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  $items = $context['items'];
  if ($items instanceof \Drupal\Core\Field\FieldItemListInterface) {
    $field_definition = $items->getFieldDefinition();
    if ($field_definition->getType() == 'string_long') {
      // https://helpdesk.eaudeweb.ro/issues/5556
      // All textareas should be limited to a certain number of characters.
      $element['#maxlength_js'] = $element['value']['#maxlength_js'] = TRUE;
      $element['#attributes']['maxlength'] = $element['value']['#attributes']['maxlength'] = 2000;
      $element['#attributes']['maxlength_js_label'][] = $element['value']['#attributes']['maxlength_js_label'][] = t('@remaining characters left.');
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function iucn_assessment_node_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  // The revision edit page is actually the node edit page.
  // We need to change the form entity to the selected revision.
  if ($entity->bundle() == 'site_assessment' && $operation == 'edit') {
    $node_revision = \Drupal::routeMatch()->getParameter('node_revision');
    if (!empty($node_revision)) {
      $form_state->getFormObject()->setEntity($node_revision);
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function iucn_assessment_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type) {
    $constraints = $entity_type->getConstraints();
    unset($constraints['EntityUntranslatableFields']);
    $entity_type->setConstraints($constraints);
  }
}

/**
 * Implements hook_validation_constraint_alter().
 */
function iucn_assessment_validation_constraint_alter(array &$definitions) {
  if (isset($definitions['EntityChanged'])) {
    $definitions['EntityChanged']['class'] = 'Drupal\iucn_assessment\Plugin\Validation\Constraint\IucnAssessmentEntityChangedConstraint';
  }
}

/**
 * Implements hook_entity_type_build().
 */
function iucn_assessment_entity_type_build(array &$entity_types) {
  $entity_types['node']->setFormClass('state_change', 'Drupal\node\NodeForm');
  $entity_types['node']->setFormClass('assign_users', 'Drupal\node\NodeForm');
  $entity_types['node']->setFormClass('assign_users', 'Drupal\node\NodeForm');

  $entity_types['node']->setFormClass('iucn_modal_field_diff', '\Drupal\iucn_assessment\Form\IucnModalFieldDiffForm');
  $entity_types['paragraph']->setFormClass('iucn_modal_paragraph_edit', '\Drupal\iucn_assessment\Form\IucnModalParagraphEditForm');
  $entity_types['paragraph']->setFormClass('iucn_modal_paragraph_add', '\Drupal\iucn_assessment\Form\IucnModalParagraphAddForm');
  $entity_types['paragraph']->setFormClass('iucn_modal_paragraph_diff', '\Drupal\iucn_assessment\Form\IucnModalParagraphDiffForm');
}

/**
 * Implements hook_entity_operation().
 */
function iucn_assessment_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'site_assessment') {
    // Add the available transitions as entity operations.
    $transitions = \Drupal::entityTypeManager()
      ->getStorage('workflow_config_transition')
      ->loadByProperties(['from_sid' => $entity->field_state->value]);
    /** @var \Drupal\workflow\Entity\WorkflowConfigTransition $transition */
    $current_account = \Drupal::currentUser();
    $current_user = User::load($current_account->id());
    /** @var \Drupal\iucn_assessment\Plugin\AssessmentWorkflow $workflow_service */
    $workflow_service = \Drupal::service('iucn_assessment.workflow');

    foreach ($transitions as $transition) {
      if ($transition->getFromSid() == $transition->getToSid()
        && $transition->getFromSid() != AssessmentWorkflow::STATUS_UNDER_REVIEW) {
        continue;
      }

      /** @var \Drupal\node\NodeInterface $entity */
      if (!$transition->isAllowed($current_user) || !$workflow_service->checkAssessmentAccess($entity, 'change_state')->isAllowed()) {
        continue;
      }
      $label = $transition->label();
      if (empty($label)) {
        $to_state = WorkflowState::load($transition->getToSid());
        $label = $to_state->label();
      }
      $operations[$transition->id()] = [
        'title' => $label,
        'url' => Url::fromRoute('iucn_assessment.node.state_change', ['node' => $entity->id()]),
        'weight' => 20,
      ];
    }

    if (in_array($entity->field_state->value, AssessmentWorkflow::USER_ASSIGNMENT_STATES)
      && NodeSiteAssessmentAssignUsersForm::access($current_account, $entity)->isAllowed()) {
      $operations['assign_users'] = [
        'title' => t('Assign users'),
        'url' => Url::fromRoute('iucn_assessment.node.assign_users', ['node' => $entity->id()]),
        'weight' => 30,
      ];
    }

    // Add correct operations for reviewers.
    if ($entity->field_state->value == AssessmentWorkflow::STATUS_UNDER_REVIEW
      && !empty($reviewer_revision = $workflow_service->getReviewerRevision($entity, $current_account->id()))) {
      /** @var \Drupal\node\NodeInterface $reviewer_revision */
      $operations['edit_reviewer_revision'] = [
        'title' => t('Edit'),
        'url' => Url::fromRoute('node.revision_edit', [
          'node' => $entity->id(),
          'node_revision' => $reviewer_revision->getRevisionId(),
        ]),
        'weight' => 10,
      ];
      $operations['finish_reviewer_revision'] = [
        'title' => t('Finish reviewing'),
        'url' => Url::fromRoute('iucn_assessment.node_revision.state_change', [
          'node' => $entity->id(),
          'node_revision' => $reviewer_revision->getRevisionId(),
        ]),
        'weight' => 20,
      ];
    }
  }
  elseif ($entity->getEntityTypeId() == 'user') {
    $operations['assign'] = [
      'title' => t('Assign'),
      'url' => Url::fromRoute('iucn_assessment.user_assign', ['user' => $entity->id()]),
      'weight' => 0,
    ];
  }
  return $operations;
}

/**
 * Implements hook_entity_operation_alter().
 */
function iucn_assessment_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'site_assessment') {
    /** @var \Drupal\node\NodeInterface $entity */
    /** @var \Drupal\iucn_assessment\Plugin\AssessmentWorkflow $workflow_service */
    $workflow_service = \Drupal::service('iucn_assessment.workflow');
    // Remove the edit entity operation when it isn't actually allowed.
    if ($workflow_service->checkAssessmentAccess($entity)->isAllowed() === FALSE) {
      unset($operations['edit']);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function iucn_assessment_paragraph_update(\Drupal\paragraphs\ParagraphInterface $paragraph) {
  if ($paragraph->isNew() || !$paragraph->isDefaultRevision()) {
    // When a new paragraph is added, node_save is called for parent.
    return;
  }
  /** @var \Drupal\node\NodeInterface $parent_entity */
  $parent_entity = $paragraph->getParentEntity();
  while ($parent_entity instanceof \Drupal\paragraphs\ParagraphInterface) {
    // Values paragraphs have threat paragraphs as parents.
    $parent_entity = $parent_entity->getParentEntity();
  }
  if (!$parent_entity instanceof \Drupal\node\NodeInterface) {
    return;
  }
  if (time() - $parent_entity->getChangedTime() <= 1) {
    // We are here because of parent node save, do we don't need to save again
    // the node.
    return;
  }

  /** @var \Drupal\iucn_assessment\Plugin\AssessmentWorkflow $workflow_service */
  $workflow_service = \Drupal::service('iucn_assessment.workflow');
  // When a paragraph is edited and the parent node is new, change it to under evaluation
  // and assign it's coordinator.
  $workflow_service->setCoordinatorAndState($parent_entity, FALSE);

  $parent_entity->setChangedTime(time());
  $parent_entity->save();
}

/**
 * Implements hook_views_query_alter().
 */
function iucn_assessment_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'account_assignments' && $view->current_display == 'block_3') {
    // Reviewers' assessments.
    /** @var \Drupal\node\NodeStorageInterface $nodeStorage */
    $nodeStorage = \Drupal::entityTypeManager()->getStorage('node');
    /** @var \Drupal\iucn_assessment\Plugin\AssessmentWorkflow  $workflowService */
    $workflowService = \Drupal::service('iucn_assessment.workflow');
    $uid = \Drupal::currentUser()->id();
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if ($condition['field'] == 'node_field_data.nid') {
          $ids = $nodeStorage->getQuery()
            ->condition('type', 'site_assessment')
            ->condition('field_state', AssessmentWorkflow::STATUS_UNDER_REVIEW)
            ->condition('field_reviewers', $uid)
            ->execute();
          $options = [NULL];
          foreach ($ids as $id) {
            $node = Node::load($id);
            $revision = $workflowService->getReviewerRevision($node, $uid);
            if ($revision instanceof NodeInterface && $revision->field_state->value == AssessmentWorkflow::STATUS_UNDER_REVIEW) {
              $options[] = $node->id();
            }
          }
          $condition['value'] = $options;
          $condition['operator'] = 'IN';
        }
      }
    }
  }
}
